pyneb.utils.stellar.Zanstra Class Reference
Public Member Functions
def __init__
def z_ratio (self, T)
def Func (self, T)
def Solve (self)
Public Attributes
ion
logFlux
magStar
ionScale
Detailed Description
Definition at line 65 of file stellar.py.
Constructor & Destructor Documentation
def pyneb.utils.stellar.Zanstra.__init__ (self, ion, logFlux = -10., magStar = 10.)
Definition at line 66 of file stellar.py.
00066 def __init__(self, ion, logFlux=-10., magStar=10.):
        s = ion.upper()
        if s in ('H','HE2'):
00069 self.ion = s
        else:
            self.ion = 'H'
00072 self.logFlux = logFlux
00073 self.magStar = magStar
        if self.ion == 'H':
00076 self.ionScale = 3.95e-11
        elif self.ion == 'HE2':
            self.ionScale = 8.49e-11
Member Function Documentation
def pyneb.utils.stellar.Zanstra.Func (self, T)
Return the discriminant of the stellar Zanstra temperature function.
Definition at line 89 of file stellar.py.
References pyneb.utils.stellar.Zanstra.logFlux, pyneb.utils.stellar.Zanstra.magStar, and pyneb.utils.stellar.Zanstra.z_ratio().
Referenced by pyneb.utils.stellar.Zanstra.Solve().
00089 def Func(self, T):
        '''Return the discriminant of the stellar Zanstra temperature function.
            '''
        r_obs = pow(10,self.logFlux) / (FLUX_MAG0 * pow(10,-self.magStar/2.5))
        return r_obs - self.z_ratio(T)
def pyneb.utils.stellar.Zanstra.Solve (self)
Determine the stellar Zanstra temperature from a nebular H or He 
   emission line flux and the stellar flux density.
Definition at line 97 of file stellar.py.
References pyneb.utils.stellar.Zanstra.Func().
00097 def Solve(self):
        '''Determine the stellar Zanstra temperature from a nebular H or He
           emission line flux and the stellar flux density.
        '''
        guess = 5.e+4
        return op.broyden1(self.Func, guess)
def pyneb.utils.stellar.Zanstra.z_ratio (self, T)
Compute the ratio of the flux in a nebular emission line to the stellar 
   flux density for a given stellar (black-body) temperature T.
Definition at line 81 of file stellar.py.
References pyneb.utils.stellar.G(), pyneb.utils.stellar.Zanstra.ion, and pyneb.utils.stellar.Zanstra.ionScale.
Referenced by pyneb.utils.stellar.Zanstra.Func().
00081 def z_ratio(self, T):
        '''Compute the ratio of the flux in a nebular emission line to the stellar
           flux density for a given stellar (black-body) temperature T.
        '''
        return self.ionScale * pow(T,3) * G(self.ion, T) * (np.exp(2.665e+4/T) - 1)
Member Data Documentation
pyneb.utils.stellar.Zanstra.ion
Definition at line 69 of file stellar.py.
Referenced by pyneb.utils.stellar.Zanstra.z_ratio().
pyneb.utils.stellar.Zanstra.ionScale
Definition at line 76 of file stellar.py.
Referenced by pyneb.utils.stellar.Zanstra.z_ratio().
pyneb.utils.stellar.Zanstra.logFlux
Definition at line 72 of file stellar.py.
Referenced by pyneb.utils.stellar.Zanstra.Func().
pyneb.utils.stellar.Zanstra.magStar
Definition at line 73 of file stellar.py.
Referenced by pyneb.utils.stellar.Zanstra.Func().
The documentation for this class was generated from the following file:
pyneb/utils/stellar.py