pyneb.utils.manage_atomic_data Namespace Reference
Classes
class _ManageAtomicData
Functions
def atom2chianti
def extract_flt
def readNIST
def getLevelsNIST
def _atom_fits2ascii
def _coll_fits2ascii
Function Documentation
def pyneb.utils.manage_atomic_data._atom_fits2ascii (filename) [private]
Transform a *atom*.fits file into an *atom*.dat file.
Definition at line 629 of file manage_atomic_data.py.
References pyneb.utils.misc.roman_to_int().
00629
def _atom_fits2ascii(filename):
    """
    Transform a *atom*.fits file into an *atom*.dat file.
    """
    strs = filename.split('/')[-1].split('_')
    elem = strs[0].capitalize()
    spec = roman_to_int(strs[1])
# type = strs[2]
    pn.atomicData.setDataFile(filename.split('/')[-1])
    atom = pn.Atom(elem, spec)
    atom.printSources()
    print('')
    fileout = raw_input('Enter the name of the output file (between {0[0]}_{0[1]}_{0[2]}_ and .dat:'.format
      (strs))
    
    fout = open('{0[0]}_{0[1]}_{0[2]}_{1}.dat'.format(strs,fileout), 'w')
    fout.write('Aij\n')
# str_ = ''
# for i in np.arange(atom.NLevels):
# str_ += '1/s '
# str_ += '\n'
    str_ = '1/s ' * atom.NLevels + '\n'
    fout.write(str_)
    for a1 in atom.getA():
        str_ = ''
        for a2 in a1:
            str_ += '{0:10.7e}'.format(a2)
            str_ += ' '
        str_ += '\n'
        fout.write(str_)
    for item in atom.AtomData.AtomHeader.iteritems():
        if 'SPECTRUM' in item[0] or 'ATOM' in item[0] or 'GSCONFIG' in item[0]:
            fout.write('*** ' + item[0] + ' ' + str(item[1]) + '\n')
        if 'NOTE' in item[0]:
            if 'Energy' not in item[1]:
                N_Note = item[0].split('NOTE')[1]
                str_N_Note = str(N_Note.split('_')[0])
                fout.write('*** SOURCE' + str_N_Note + ' ' + atom.AtomData.AtomHeader.get('SOURCE'+
      str_N_Note) + '\n')
                fout.write('*** ' + item[0] + ' ' + str(item[1]) + '\n')
    
    fout.close()
    
def pyneb.utils.manage_atomic_data._coll_fits2ascii (filename, overwrite = None) [private]
Transform a *coll*.fits file into an *coll*.dat file.
Definition at line 671 of file manage_atomic_data.py.
References pyneb.utils.misc.roman_to_int(), and pyneb.utils.misc.strExtract().
00671
def _coll_fits2ascii(filename, overwrite=None):
    """
    Transform a *coll*.fits file into an *coll*.dat file.
    """
    strs = filename.split('/')[-1].split('_')
    elem = strs[0].capitalize()
    spec = roman_to_int(strs[1])
    pn.atomicData.setDataFile(filename.split('/')[-1])
    atom = pn.Atom(elem, spec)
    #atom.printSources()
    fileout = '{}.dat'.format(filename.split('.')[0])
    
    if overwrite is not True:
        if os.path.exists(fileout):
            erase = raw_input('{} exists, overwrite?'.format(fileout))
            if erase != 'y':
                return
    fout = open(fileout, 'w')
    fout.write('*** {0}{1} collision strengths data\n'.format(elem, strs[1].upper()))
    str_ = '0 0'
    for t in atom.getTemArray():
        str_ += ' {0:9.3e}'.format(t)
    str_ += '\n'
    fout.write(str_)
    for omega in atom.getOmegaArray():
        j = strExtract(omega, 'Omega(', '->')
        i = strExtract(omega, '->', ')')
        omegs = strExtract(omega, '[', ']')
        str_ = '{0} {1}'.format(i,j)
        for omeg in omegs.split():
            str_ += ' {0:9.3e}'.format(float(omeg))
        str_ += '\n'
        fout.write(str_)
        
    for item in atom.CollData.CollHeader.iteritems():
        if 'SPECTRUM' in item[0] or 'ATOM' in item[0] or 'GSCONFIG' in item[0]:
            fout.write('*** ' + item[0] + ' ' + str(item[1]) + '\n')
        if 'TUNIT1' == item[0]:
            fout.write('*** T_UNIT ' + str(item[1]) + '\n')
        if 'SOURCE' in item[0]:
            N_Source = item[0].split('SOURCE')[1]
            str_N_Source = str(N_Source.split('_')[0])
            fout.write('*** ' + item[0] + ' ' + str(item[1]) + '\n')
            try:
                fout.write('*** NOTE' + str_N_Source + ' ' + atom.CollData.CollHeader.get('NOTE'+
      str_N_Source) + '\n')
            except:
                fout.write('*** NOTE' + str_N_Source + ' collision strengths \n')
    print('{} done'.format(fileout))
    fout.close()
    
    
    
def pyneb.utils.manage_atomic_data.atom2chianti (atom)
Definition at line 9 of file manage_atomic_data.py.
References pyneb.utils.misc.parseAtom().
Referenced by pyneb.utils.pn_chianti.get_levs_order(), pyneb.utils.manage_atomic_data._ManageAtomicData.getAllAvailableFiles(), and pyneb.utils.manage_atomic_data._ManageAtomicData.getDirForFile().
00009
def atom2chianti(atom):
    elem = parseAtom(atom)[0]
    spec = int(parseAtom(atom)[1])
    return '{0}_{1}'.format(elem.lower(), spec)
def pyneb.utils.manage_atomic_data.extract_flt (str_)
Return the first float in str_, removing the no digit (and no dot) leading part of it.
Ex:
extract_flt('123.00?') -> 123.00
Definition at line 539 of file manage_atomic_data.py.
References pyneb.utils.misc.bs().
00539
def extract_flt(str_):
    """
    Return the first float in str_, removing the no digit (and no dot) leading part of it.
    Ex:
    extract_flt('123.00?') -> 123.00
    """
    res = ''
    for l in bs(str_):
        if l.isdigit() or l == '.':
            res += l
        else:
            break
    if res == '':
        return np.nan
    else:
        return float(res)
def pyneb.utils.manage_atomic_data.getLevelsNIST (atom, NLevels = None)
Return a numpy.array containing the NIST data related to the levels for the given atom
The keys of the recarry are: conf, term, J, energy, ref
Example:
    data = getLevelsNIST('O3')
    energies = data['energy']
Definition at line 606 of file manage_atomic_data.py.
References pyneb.utils.misc.execution_path(), pyneb.utils.misc.int_to_roman(), pyneb.utils.misc.parseAtom(), and pyneb.utils.manage_atomic_data.readNIST().
Referenced by pyneb.utils.apap.apap2ascii(), and pyneb.utils.pn_chianti.get_levs_order().
00606
def getLevelsNIST(atom, NLevels = None):
    """
    Return a numpy.array containing the NIST data related to the levels for the given atom
    The keys of the recarry are: conf, term, J, energy, ref
    Example:
        data = getLevelsNIST('O3')
        energies = data['energy']
    """
    elem, spec = parseAtom(atom)
    elem = elem.lower()
    spec = int_to_roman(int(spec)).lower()
    atom_str = '{0}_{1}'.format(elem, spec)
    level_file = '{0}_levels.dat'.format(atom_str)
    file_ = execution_path('../atomic_data/levels/{0}'.format(level_file))
    if os.path.isfile(file_):
        data = readNIST(file_, NLevels=NLevels)
        pn.log_.message('Reading energies and stat weights from {0}'.format(level_file), calling='
      getLevelsNIST')
        return data
    else:
        return None
    
    
def pyneb.utils.manage_atomic_data.readNIST (NISTfile, NLevels = None)
The NIST levels file must be obtained from this page:
    http://physics.nist.gov/PhysRefData/ASD/levels_form.html
with the following options:
    Level Units: cm-1
    Format output: ASCIIda
    Display output: in its entirely
    Energy ordered
    Level Information: Principal configuration, Principal term, Level, J
    Bibliographic references
Definition at line 557 of file manage_atomic_data.py.
Referenced by pyneb.utils.manage_atomic_data.getLevelsNIST().
00557
def readNIST(NISTfile,NLevels=None):
    """
    The NIST levels file must be obtained from this page:
        http://physics.nist.gov/PhysRefData/ASD/levels_form.html
    with the following options:
        Level Units: cm-1
        Format output: ASCIIda
        Display output: in its entirely
        Energy ordered
        Level Information: Principal configuration, Principal term, Level, J
        Bibliographic references
    """
    data = np.genfromtxt(NISTfile, comments = '-',
                    delimiter = '|', names = 'conf, term, J, energy, ref',
                    dtype=('a23', 'a9', 'a4', 'float', 'a10'), autostrip=True,
                    converters = {'energy':extract_flt, 'J':bs, 'conf':bs, 'term': bs, 'ref':bs})
    data = data[data['J'] != '']
    previous_ref = ''
    previous_conf = ''
    previous_term = ''
    for d in data:
        if d['conf'] == '':
            d['conf'] = previous_conf
        else:
            previous_conf = d['conf']
        if d['term'] == '':
            d['term'] = previous_term
        else:
            previous_term = d['term']
        if d['ref'] == '':
            d['ref'] = previous_ref
        else:
            previous_ref = d['ref']
        if '?' in d['J']:
            d['J'] = d['J'].split('?')[0]
        if d['J'] == '':
            d['J'] = 0.
        elif '/' in d['J']:
            d['J'] = '{0:.1f}'.format(float(d['J'].split('/')[0]) / float(d['J'].split('/')[1]))
        else:
            d['J'] = '{0:.1f}'.format(float(d['J']))
           
    data = data[data['energy'].argsort()]
    data = data.astype([('conf', 'a23'), ('term', 'a9'), ('J', 'float'), ('energy', 'float'), ('ref', 'a10'
      )])
    if NLevels is not None:
        data = data[0:NLevels]
    return data