pyneb.utils.stellar Namespace Reference
Classes
class Zanstra
Functions
def logL (V, D_pc, T_eff)
def BC (T_eff)
def integrand (x)
def G (ion, T)
Variables
float WAV_H_IONIZ = 911.7634
int WAV_HE2_IONIZ = WAV_H_IONIZ/4
float ABMAG0 = 48.60
float STMAG0 = 21.10
float FLUX_MAG0 = 3.63e-9
float MBOL_Sun = 4.75
Function Documentation
def pyneb.utils.stellar.BC (T_eff)
Bolometric correction for very hot stars, from Vacca, Garmany & Shull,
   1996, ApJ, 460, 914.
Definition at line 37 of file stellar.py.
Referenced by pyneb.utils.stellar.logL().
00037 def BC(T_eff):
    '''Bolometric correction for very hot stars, from Vacca, Garmany & Shull,
       1996, ApJ, 460, 914.
    '''
    return 27.66 - 6.84*np.log10(T_eff)
# return 28.46 - 7.08*np.log10(T_eff) + 0.08*log_g # Fit incl. gravity
def pyneb.utils.stellar.G (ion, T)
Compute integral over frequency for Planck function.
   ion - Reference Ion ("H | HE')
   T   - Stellar temperature (K)
   See Pottasch (1984), p. 169, eq. VII-8 for details. 
Definition at line 47 of file stellar.py.
Referenced by pyneb.utils.stellar.Zanstra.z_ratio().
00047 def G(ion,T):
    '''Compute integral over frequency for Planck function.
       ion - Reference Ion ("H | HE')
       T - Stellar temperature (K)
       See Pottasch (1984), p. 169, eq. VII-8 for details.
    '''
    if ion.upper()=='H':
        nu = phy.c / (WAV_H_IONIZ*1.e-10)
    elif ion.upper()=='HE2':
        nu = phy.c / (WAV_HE2_IONIZ*1.e-10)
    else:
        print 'Unrecognized ion: %s' % ion
        return None
    return quad(integrand, phy.h*nu/(phy.k*T), np.Inf)[0]
def pyneb.utils.stellar.integrand (x)
Definition at line 44 of file stellar.py.
00044 def integrand(x):
    return x**2/(np.exp(x)-1)
def pyneb.utils.stellar.logL (V, D_pc, T_eff)
Calculate the stellar luminosity in Solar units, given an (unreddened) V 
   apparent magnitude, a distance (pc), and the stellar temperature (K).
Definition at line 30 of file stellar.py.
References pyneb.utils.stellar.BC().
00030 def logL(V, D_pc, T_eff):
    '''Calculate the stellar luminosity in Solar units, given an (unreddened) V
       apparent magnitude, a distance (pc), and the stellar temperature (K).
    '''
    return -0.4*(V - 2.5*np.log10(D_pc) + BC(T_eff) - MBOL_Sun)
Variable Documentation
float pyneb.utils.stellar.ABMAG0 = 48.60
Definition at line 13 of file stellar.py.
float pyneb.utils.stellar.FLUX_MAG0 = 3.63e-9
Definition at line 16 of file stellar.py.
float pyneb.utils.stellar.MBOL_Sun = 4.75
Definition at line 17 of file stellar.py.
float pyneb.utils.stellar.STMAG0 = 21.10
Definition at line 14 of file stellar.py.
float pyneb.utils.stellar.WAV_H_IONIZ = 911.7634
Definition at line 11 of file stellar.py.
int pyneb.utils.stellar.WAV_HE2_IONIZ = WAV_H_IONIZ/4
Definition at line 12 of file stellar.py.