pyneb.core.emisGrid Namespace Reference
Classes
class EmisGrid
Functions
def getEmisGridDict
Function Documentation
def pyneb.core.emisGrid.getEmisGridDict (elem_list = None, spec_list = None, atom_list = None, restore = True, pypic_path = None, n_tem = 100, n_den = 100, tem_min = 5000., tem_max = 20000., den_min = 10., den_max = 1e8, save = True, atomDict = None, createPypicsDir = True, computeIfAbsent = True)
Return a dictionary of EmisGrid objects referred to by their atom string (e.g. 'O3').

Usage:
    emisgrids = pn.getEmisGridDict(['C', 'N', 'O'], [2, 3], save=True)
    emisgrids = pn.getEmisGridDict(atom_list=['N2', 'O2', 'O3'], pypic_path='/tmp/pypics/',
                    den_max = 1e6)
    emisgrids = pn.getEmisGridDict(atomDict=diags.atomDict)

Parameters:
    - elem_list         list of elements
    - spec_list         list of spectrum values (integers)
    - atom_list         list of atoms (e.g. ['N2', 'O3'])
    - restore           Boolean. If True (default), the program will search for a previously computed grid.
                        If not found, it will compute the EmisGrid (unless computeIfAbsent is set to False)
    - pypic_path        directory where to look for the pypic emissivity files. It defaults to pn.config.pypic_path, 
                        which is defined when the PyNeb session begins and corresponds to $HOME/.pypics if
                        the ENVIRONMENT variable HOME is accessible or to /tmp/pypics otherwise
    - n_tem, n_den      number of points in the Te and Ne samples resp. 
    - tem_min, tem_max, den_min, den_max    limits for Te and Ne
    - save              Boolean. If True (default), the emissivity grid will be saved. It has no effect if the 
                        EmisGrid has just been restored.
    - atomDict          dictionary of Atom objects
    - computeIfAbsent   If the file to restore is absent and this parameter is True (default), the 
                        EmisGrid is computed
Definition at line 312 of file emisGrid.py.
References pyneb.utils.misc.parseAtom(), and pyneb.utils.saverestore.save().
Referenced by pyneb.core.emisGrid.EmisGrid.plotLineRatio().
00312 atomDict=None, createPypicsDir=True, computeIfAbsent=True):
    """
    Return a dictionary of EmisGrid objects referred to by their atom string (e.g. 'O3').
    Usage:
        emisgrids = pn.getEmisGridDict(['C', 'N', 'O'], [2, 3], save=True)
        emisgrids = pn.getEmisGridDict(atom_list=['N2', 'O2', 'O3'], pypic_path='/tmp/pypics/',
                        den_max = 1e6)
        emisgrids = pn.getEmisGridDict(atomDict=diags.atomDict)
    Parameters:
        - elem_list list of elements
        - spec_list list of spectrum values (integers)
        - atom_list list of atoms (e.g. ['N2', 'O3'])
        - restore Boolean. If True (default), the program will search for a previously computed
       grid.
                            If not found, it will compute the EmisGrid (unless computeIfAbsent is set to
       False)
        - pypic_path directory where to look for the pypic emissivity files. It defaults to
       pn.config.pypic_path,
                            which is defined when the PyNeb session begins and corresponds to $HOME/.pypics
       if
                            the ENVIRONMENT variable HOME is accessible or to /tmp/pypics otherwise
        - n_tem, n_den number of points in the Te and Ne samples resp.
        - tem_min, tem_max, den_min, den_max limits for Te and Ne
        - save Boolean. If True (default), the emissivity grid will be saved. It has no effect
       if the
                            EmisGrid has just been restored.
        - atomDict dictionary of Atom objects
        - computeIfAbsent If the file to restore is absent and this parameter is True (default), the
                            EmisGrid is computed
    """
    if pypic_path is None:
        pypic_path = pn.config.pypic_path
    else:
        pn.config.pypic_path = pypic_path
    calling = 'getEmisGridDict'
    if pypic_path is None:
        return None
    emis_grids = {}
    atoms = []
    if atomDict is not None:
        atoms = atomDict.keys()
    else:
        if atom_list is not None:
            atoms = atom_list
        else:
# VL Removed 13 March 2015 because it made the code ignore the elem keyword
# atoms = pn.atomicData.getAllAtoms()
            if (elem_list is None) and (spec_list is None):
                atoms = pn.atomicData.getAllAtoms()
            else:
                for elem in elem_list:
                    for spec in spec_list:
                        atoms.append(elem + str(spec))
    for atom in atoms:
        elem, spec = parseAtom(atom)
        file_ = '{0}/emis_{1}{2}.pypic'.format(pypic_path, elem, spec)
        if atomDict is not None:
            atomObj = atomDict[atom]
        else:
            atomObj = None
        if restore:
            if os.path.exists(file_):
                try:
                    emis_grids[elem + spec] = EmisGrid(restore_file=file_, atomObj=atomObj)
                    pn.log_.message('Read %s' % file_, calling=calling)
                    compute_this = False
                except:
                    if computeIfAbsent:
                        pn.log_.warn('Wrong emission map: {0}, creating it'.format(file_), calling=calling)
                        compute_this = True
                    else:
                        pn.log_.error('Wrong emission map: {0}'.format(file_), calling=calling)
                        compute_this = False
            else:
                pn.log_.warn('Emission map not found: {0}'.format(file_), calling=calling)
                if computeIfAbsent:
                    compute_this = True
        else:
            compute_this = True
        if compute_this:
            try:
                emis_grids[atom] = EmisGrid(elem, spec, n_tem=n_tem, n_den=n_den, tem_min=tem_min,
      tem_max=tem_max,
                                              den_min=den_min, den_max=den_max, atomObj=atomObj)
                if save:
                    emis_grids[atom].save(file_)
                    pn.log_.message('%s saved to %s' % ((atom), file_), calling=calling)
            except:
                pn.log_.warn('No %s EmisGrid' % (atom), calling=calling)
    return emis_grids