pyneb.core.pynebcore Namespace Reference
Classes
class _AtomDataAscii
class _AtomDataFits
class _AtomDataNone
class _CollDataAscii
class _CollDataFits
class _CollDataNone
class Atom
class EmissionLine
class Observation
class RecAtom
Functions
def profile (f)
def getRecEmissivity
def getHbEmissivity
def getAtomDict (atom_list=None, elem_list=None, spec_list=None, kwargs)
def getLineLabel
def parseLineLabel (lineLabel)
def isValid (line_label)
Variables
profiler = None
Detailed Description
@module pynebcore
Main PyNeb module
Tools to manage atoms, emission lines and observational data.

@class Atom           atom object
@class EmissionLine   emission line object
@class Observation    observation object
Function Documentation
def pyneb.core.pynebcore.getAtomDict (atom_list = None, elem_list = None, spec_list = None, kwargs)
Initializes all atoms, according to the atomic files available.
The elem objects are given conventional names elem+spec (e.g., O III is O3)

Usage:
    all = pn.getAtomDict()
    print all['S2'].name
    some = pn.getAtomDict(elem_list=['C', 'N', 'O'])
    some = pn.getAtomDict(atom_list=['O2', 'O3', 'Ar3'])

Parameters:
    - atom_list     a list of the ions for which the elem is to be computed 
                    Takes precedence on elem_list and spec_list
    - elem_list     a list of all the elements for which the elem is to be computed (all by default)
    - spec_list     a list of the spectra for which the elem is to be computed (all by default)
    _ **kwargs      argumentas passed to Atom, e.g. OmegaInterp
Definition at line 3092 of file pynebcore.py.
References pyneb.utils.misc.parseAtom().
03092 def getAtomDict(atom_list=None, elem_list=None, spec_list=None, **kwargs):
    """
    Initializes all atoms, according to the atomic files available.
    The elem objects are given conventional names elem+spec (e.g., O III is O3)
    Usage:
        all = pn.getAtomDict()
        print all['S2'].name
        some = pn.getAtomDict(elem_list=['C', 'N', 'O'])
        some = pn.getAtomDict(atom_list=['O2', 'O3', 'Ar3'])
    Parameters:
        - atom_list a list of the ions for which the elem is to be computed
                        Takes precedence on elem_list and spec_list
        - elem_list a list of all the elements for which the elem is to be computed (all by default)
        - spec_list a list of the spectra for which the elem is to be computed (all by default)
        _ **kwargs argumentas passed to Atom, e.g. OmegaInterp
    """
    all_atoms = {}
    if atom_list is None:
        if spec_list is None:
            spec_list = SPEC_LIST
        if elem_list is None:
            atom_list = pn.atomicData.getAllAtoms()
        else:
            atom_list = []
            for elem in elem_list:
                for spec in spec_list:
                    atom_list.append(elem + str(spec))
    for atom in atom_list:
        elem, spec = parseAtom(atom)
        try:
            all_atoms[atom] = pn.Atom(elem, spec, **kwargs)
            pn.log_.message('Including ' + atom, calling='getAtomDict')
        except:
            pn.log_.message(atom + ' not found', calling='getAtomDict')
    return all_atoms
def pyneb.core.pynebcore.getHbEmissivity (tem = -1)
Compute Hbeta emissivity in erg/s/(N(H+)*N(e-)) for a given temperature with the formula 
    by Aller (1984)

Usage:
    getHbemissivity(tem=10000)

Parameters:
    - tem     electronic temperature in K
Definition at line 3071 of file pynebcore.py.
Referenced by pyneb.core.pynebcore.getRecEmissivity().
03071 def getHbEmissivity(tem= -1):
    """
    Compute Hbeta emissivity in erg/s/(N(H+)*N(e-)) for a given temperature with the formula
        by Aller (1984)
    Usage:
        getHbemissivity(tem=10000)
    Parameters:
        - tem electronic temperature in K
    """
    tem4 = np.asarray(tem) * 1.0e-4
    j_hb = 1.387 / pow(tem4, 0.983) / pow(10., 0.0424 / tem4) * 1.e-25
    # Remove jhb for tem4 < 0 or tem4 > 1e2
    ((tem4 < 0.) | (tem4 > 1e2)).choose(j_hb, -1)
    return j_hb
def pyneb.core.pynebcore.getLineLabel (elem, spec, wave, blend = False)
Build a line label in the standard PyNeb format. Return atom_label, wave_label, and line_label 
        (strings representing the atom and wave fragments of the line label and the 
            complete line label)

Parameters:
    - elem      symbol of the selected element
    - spec      ionization stage in spectroscopic notation (I = 1, II = 2, etc.)
    - wave      wavelength of the line
    - blend     blend flag (default = False)

@see parseLineLabel
Definition at line 3134 of file pynebcore.py.
Referenced by pyneb.core.pynebcore.Observation.getLine().
03134 def getLineLabel(elem, spec, wave, blend=False):
    """
    Build a line label in the standard PyNeb format. Return atom_label, wave_label, and line_label
            (strings representing the atom and wave fragments of the line label and the
                complete line label)
    Parameters:
        - elem symbol of the selected element
        - spec ionization stage in spectroscopic notation (I = 1, II = 2, etc.)
        - wave wavelength of the line
        - blend blend flag (default = False)
    @see parseLineLabel
    """
    if isinstance(wave, str):
        wave_label = wave
    else:
        wave4 = wave / 1.e4
        if wave < 10000.:
            wave_label = "{0:.0f}A".format(wave)
        else:
            wave_label = "{0:.1f}m".format(wave4)
    atom_label = elem + str(spec)
    if blend:
        blend_flag = '+'
    else:
        blend_flag = ''
    line_label = atom_label + '_' + wave_label + blend_flag
    return atom_label, wave_label, line_label
def pyneb.core.pynebcore.getRecEmissivity (tem, den, lev_i = None, lev_j = None, atom = 'H1', method = 'linear', wave = None, product = True)
The function instantiates a RecAtom and store it into pn.atomicData._RecombData for a further use.
More possibilities are obtained using the RecAtom class.

Usage:
    print getRecEmissivity(1e4, 1e3, 3, 2, atom='H1') / getRecEmissivity(1e4, 1e3, 4, 2, atom='H1')  
        # return Ha/Hb 

Parameters:
    - tem           temperature in K
    - den           density in cm-3
    - lev_i, lev_j  levels (lev_i>lev_j, i_min=1)
    - atom          atom (e.g. 'H1', 'He1')
    - method        interpolation method ('linear', 'nearest', 'cubic'), sent to scipy.interpolate.griddata
    - wave          alternative way of identifying emision line.
Definition at line 3036 of file pynebcore.py.
References pyneb.core.pynebcore.getHbEmissivity(), and pyneb.utils.misc.parseAtom().
Referenced by pyneb.core.pynebcore.Atom.getIonAbundance(), and pyneb.core.pynebcore.RecAtom.getIonAbundance().
03036 def getRecEmissivity(tem, den, lev_i=None, lev_j=None, atom='H1', method='linear',
      wave=None, product=True):
    """
    The function instantiates a RecAtom and store it into pn.atomicData._RecombData for a further use.
    More possibilities are obtained using the RecAtom class.
    Usage:
        print getRecEmissivity(1e4, 1e3, 3, 2, atom='H1') / getRecEmissivity(1e4, 1e3, 4, 2, atom='H1')
            # return Ha/Hb
    Parameters:
        - tem temperature in K
        - den density in cm-3
        - lev_i, lev_j levels (lev_i>lev_j, i_min=1)
        - atom atom (e.g. 'H1', 'He1')
        - method interpolation method ('linear', 'nearest', 'cubic'), sent to
       scipy.interpolate.griddata
        - wave alternative way of identifying emision line.
    """
    calling = 'getRecEmissivity'
    
    if pn.config.INSTALLED['scipy']:
        elem, spec = parseAtom(atom)
    
        if atom not in pn.atomicData._RecombData:
            pn.atomicData._RecombData[atom] = RecAtom(elem, spec)
        return pn.atomicData._RecombData[atom].getEmissivity(tem=tem, den=den, lev_i=lev_i, lev_j=lev_j,
                                                             method=method, wave=wave, product=product)
    else:
        if (atom == 'H1') and (lev_i == 4) and (lev_j == 2):
            pn.log_.warn('Scipy is missing, {0} returning Hbeta'.format(calling), calling)
            return getHbEmissivity(tem)
        else:
            pn.log_.error('Only Hbeta emissivity available, as scipy not installed', calling)
def pyneb.core.pynebcore.isValid (line_label)
Return True if the line label correspond to a valid line from LINE_LABEL_LIST or BLEND_LIST

Usage:
    isValid('O3_5007A')

Parameters:
    - line_label    label to be tested
Definition at line 3213 of file pynebcore.py.
References pyneb.core.pynebcore.parseLineLabel().
03213 def isValid(line_label):
    """
    Return True if the line label correspond to a valid line from LINE_LABEL_LIST or BLEND_LIST
    Usage:
        isValid('O3_5007A')
    Parameters:
        - line_label label to be tested
    """
    elem, spec, atom, wave, waveLabel, blend = parseLineLabel(line_label)
    if atom in LINE_LABEL_LIST:
            if (waveLabel in LINE_LABEL_LIST[atom]) or (line_label in BLEND_LIST):
                is_valid = True
            else:
                is_valid = False
    else:
        is_valid = False
    return is_valid
def pyneb.core.pynebcore.parseLineLabel (lineLabel)
Parse the line label to extract the substrings referring to the atom (elem, spec and atom)
and the numerical value of the wave

Parameters:
    - label    line label in the standard PyNeb format

Returns:
    - elem, spec, atom_label, wave, wave_label, blend  strings containing the elem, spec, atom and 
                                                          wave; numerical value of the wave, 
                                                          in Angstrom; and blend flag 
Todo
Todo maybe rearrange the order so 1) it is compatible with getLineLabel, or 2) it lists all the strings first
Definition at line 3167 of file pynebcore.py.
References pyneb.utils.misc.parseAtom(), and pyneb.utils.misc.strExtract().
Referenced by pyneb.core.pynebcore.isValid().
03167 def parseLineLabel(lineLabel):
    """
    Parse the line label to extract the substrings referring to the atom (elem, spec and atom)
    and the numerical value of the wave
    Parameters:
        - label line label in the standard PyNeb format
    Returns:
        - elem, spec, atom_label, wave, wave_label, blend strings containing the elem, spec, atom and
                                                              wave; numerical value of the wave,
                                                              in Angstrom; and blend flag
    """
    ##
    # @todo maybe rearrange the order so 1) it is compatible with getLineLabel, or 2) it lists all the
       strings first
    # determine if the line is a blend or not
    if lineLabel[-1] == '+' or lineLabel[-2] == '+':
        blend = True
    else:
        blend = False
    # extract information on the atom
    elem_spec = strExtract(lineLabel, ' ', '_')
    elem, spec = parseAtom(elem_spec)
    atom_label = elem + str(spec)
    if len(elem_spec) > 0:
        if elem_spec[-1] == 'r':
            atom_label += 'r'
    # extract information on the wave
    if blend:
        try:
            wave = float(strExtract(lineLabel[:-2], '_', ' '))
        except:
            wave = 0.
    else:
        try:
            wave = float(strExtract(lineLabel[:-1], '_', ' '))
        except:
            wave = 0.
    wave_label = strExtract(lineLabel, '_', ' ')
    if lineLabel[-1] == 'm':
        wave = wave * 1.e4
    
    return elem, spec, atom_label, wave, wave_label, blend
    
def pyneb.core.pynebcore.profile (f)
Definition at line 43 of file pynebcore.py.
00043 def profile(f):
            return f
Variable Documentation
pyneb.core.pynebcore.profiler = None
Definition at line 38 of file pynebcore.py.