name: test
on:
  pull_request:
    branches:
      - master
      - main
      - devel

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x
      - name: Install dependencies
        run: python -m pip install --upgrade pip pyneb
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests --doctest-modules --junitxml=junit/test-results.xml